executable = "fusion9"
schema = "avalon-core:application-1.0"
application_dir = "fusion"
label = "Fusion"
label_variant = "9"
ftrack_label = "Fusion"
icon = "app_icons/fusion.png"
ftrack_icon = '{}/app_icons/fusion.png'
launch_hook = "pype/hooks/fusion/prelaunch.py/FusionPrelaunch"
